// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartLicenseAPI.Data;

#nullable disable

namespace SmartLicenseAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SmartLicenseAPI.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassingScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Theory examination for driving license",
                            DurationMinutes = 60,
                            IsActive = true,
                            PassingScore = 35,
                            Title = "Driving License Theory Exam",
                            TotalQuestions = 50
                        });
                });

            modelBuilder.Entity("SmartLicenseAPI.Models.ExamAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExamSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedAnswer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExamSessionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("ExamAnswers");
                });

            modelBuilder.Entity("SmartLicenseAPI.Models.ExamSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedQuestions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExamId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamSessions");
                });

            modelBuilder.Entity("SmartLicenseAPI.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Traffic Signs",
                            CorrectAnswer = "Stop",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Stop\", \"Go\", \"Slow down\", \"Turn right\"]",
                            Points = 1,
                            QuestionText = "What does a red traffic light mean?"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Road Rules",
                            CorrectAnswer = "30 km/h",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"20 km/h\", \"30 km/h\", \"40 km/h\", \"50 km/h\"]",
                            Points = 1,
                            QuestionText = "What is the speed limit in a school zone?"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Road Rules",
                            CorrectAnswer = "Before turning or changing lanes",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Only on highways\", \"Before turning or changing lanes\", \"Only at night\", \"Never\"]",
                            Points = 1,
                            QuestionText = "When should you use your turn signal?"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Traffic Signs",
                            CorrectAnswer = "Stop if safe",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Speed up\", \"Stop if safe\", \"Go\", \"Turn left\"]",
                            Points = 1,
                            QuestionText = "What does a yellow traffic light mean?"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Road Rules",
                            CorrectAnswer = "0.08%",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"0.00%\", \"0.05%\", \"0.08%\", \"0.10%\"]",
                            Points = 1,
                            QuestionText = "What is the legal blood alcohol limit for drivers?"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Road Rules",
                            CorrectAnswer = "Stop for pedestrians",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Speed up\", \"Honk\", \"Stop for pedestrians\", \"Ignore it\"]",
                            Points = 1,
                            QuestionText = "What should you do at a pedestrian crossing?"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Traffic Signs",
                            CorrectAnswer = "Come to complete stop",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Slow down\", \"Yield\", \"Come to complete stop\", \"Go if clear\"]",
                            Points = 1,
                            QuestionText = "What does a stop sign mean?"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Road Rules",
                            CorrectAnswer = "When safe and legal",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"On curves\", \"When safe and legal\", \"In tunnels\", \"At intersections\"]",
                            Points = 1,
                            QuestionText = "When can you overtake another vehicle?"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Road Rules",
                            CorrectAnswer = "3 seconds",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"1 second\", \"2 seconds\", \"3 seconds\", \"5 seconds\"]",
                            Points = 1,
                            QuestionText = "What is the minimum following distance?"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Traffic Signs",
                            CorrectAnswer = "Mandatory instruction",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Warning\", \"Prohibition\", \"Mandatory instruction\", \"Information\"]",
                            Points = 1,
                            QuestionText = "What does a circular blue sign indicate?"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Road Rules",
                            CorrectAnswer = "Both A and B",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Only at night\", \"In fog and rain\", \"Both A and B\", \"Never during day\"]",
                            Points = 1,
                            QuestionText = "When should headlights be used?"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Road Rules",
                            CorrectAnswer = "Give way to vehicles already in roundabout",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Give way to vehicles already in roundabout\", \"Speed up\", \"Go straight\", \"Stop completely\"]",
                            Points = 1,
                            QuestionText = "What is the correct way to enter a roundabout?"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Road Markings",
                            CorrectAnswer = "You may overtake if safe",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"No overtaking\", \"You may overtake if safe\", \"Stop\", \"Pedestrian crossing\"]",
                            Points = 1,
                            QuestionText = "What does a broken white line mean?"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Emergency",
                            CorrectAnswer = "Pump brakes and use handbrake",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Jump out\", \"Pump brakes and use handbrake\", \"Speed up\", \"Close eyes\"]",
                            Points = 1,
                            QuestionText = "What should you do if your brakes fail?"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Vehicle Knowledge",
                            CorrectAnswer = "Prevent wheel lock during braking",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Increase speed\", \"Prevent wheel lock during braking\", \"Save fuel\", \"Cool engine\"]",
                            Points = 1,
                            QuestionText = "What is the purpose of ABS?"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Road Rules",
                            CorrectAnswer = "Before changing lanes or turning",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Only when reversing\", \"Before changing lanes or turning\", \"Once per trip\", \"Never\"]",
                            Points = 1,
                            QuestionText = "When should you check your mirrors?"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Traffic Signs",
                            CorrectAnswer = "Warning",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Information\", \"Warning\", \"Mandatory\", \"Prohibition\"]",
                            Points = 1,
                            QuestionText = "What does a triangular road sign indicate?"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Road Rules",
                            CorrectAnswer = "Turn wheels and use handbrake",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Leave in neutral\", \"Turn wheels and use handbrake\", \"Leave engine running\", \"Park in middle of road\"]",
                            Points = 1,
                            QuestionText = "What is the safe way to park on a hill?"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Road Markings",
                            CorrectAnswer = "No parking or overtaking",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Parking allowed\", \"No parking or overtaking\", \"School zone\", \"Bus lane\"]",
                            Points = 1,
                            QuestionText = "What does a double yellow line mean?"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Road Rules",
                            CorrectAnswer = "At all times by all passengers",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Only on highways\", \"Only in front seats\", \"At all times by all passengers\", \"Only by driver\"]",
                            Points = 1,
                            QuestionText = "When should seat belts be worn?"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Vehicle Knowledge",
                            CorrectAnswer = "Tires losing contact with wet road",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Engine overheating\", \"Tires losing contact with wet road\", \"Brake failure\", \"Steering problem\"]",
                            Points = 1,
                            QuestionText = "What is aquaplaning?"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Road Rules",
                            CorrectAnswer = "Stop, look, and listen",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Speed up\", \"Stop, look, and listen\", \"Honk\", \"Ignore signals\"]",
                            Points = 1,
                            QuestionText = "What should you do at a railway crossing?"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Traffic Signs",
                            CorrectAnswer = "Proceed in arrow direction",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Stop\", \"Proceed in arrow direction\", \"Yield\", \"No entry\"]",
                            Points = 1,
                            QuestionText = "What does a green arrow traffic light mean?"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Vehicle Knowledge",
                            CorrectAnswer = "Weekly or before long trips",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Once a year\", \"Weekly or before long trips\", \"Never\", \"Only when flat\"]",
                            Points = 1,
                            QuestionText = "How often should tire pressure be checked?"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Vehicle Knowledge",
                            CorrectAnswer = "Area not visible in mirrors",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Area visible in mirrors\", \"Area not visible in mirrors\", \"Front windscreen\", \"Dashboard\"]",
                            Points = 1,
                            QuestionText = "What is the blind spot?"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Road Rules",
                            CorrectAnswer = "Only in heavy fog",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"At night always\", \"Only in heavy fog\", \"In rain\", \"All the time\"]",
                            Points = 1,
                            QuestionText = "When should fog lights be used?"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Traffic Signs",
                            CorrectAnswer = "Slow down and yield to traffic",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Stop completely\", \"Slow down and yield to traffic\", \"Speed up\", \"No entry\"]",
                            Points = 1,
                            QuestionText = "What does 'Give Way' sign mean?"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Road Rules",
                            CorrectAnswer = "9 and 3 o'clock",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"12 o'clock\", \"9 and 3 o'clock\", \"Bottom of wheel\", \"One hand only\"]",
                            Points = 1,
                            QuestionText = "What is the correct position for hands on steering wheel?"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Emergency",
                            CorrectAnswer = "Hold steering firmly and slow gradually",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Brake hard\", \"Hold steering firmly and slow gradually\", \"Accelerate\", \"Jump out\"]",
                            Points = 1,
                            QuestionText = "What should you do if a tire blows out?"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Traffic Signs",
                            CorrectAnswer = "No entry",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Stop\", \"No entry\", \"Give way\", \"Speed limit\"]",
                            Points = 1,
                            QuestionText = "What does a red circle with white bar mean?"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Road Rules",
                            CorrectAnswer = "Only with hands-free device",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Anytime\", \"Only with hands-free device\", \"At traffic lights\", \"On highways\"]",
                            Points = 1,
                            QuestionText = "When is it legal to use a mobile phone while driving?"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Vehicle Knowledge",
                            CorrectAnswer = "Warn others of emergency or hazard",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"To look cool\", \"Warn others of emergency or hazard\", \"For parking\", \"To signal turn\"]",
                            Points = 1,
                            QuestionText = "What is the purpose of hazard lights?"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Road Rules",
                            CorrectAnswer = "Check for traffic and cyclists",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Open quickly\", \"Check for traffic and cyclists\", \"Honk\", \"Flash lights\"]",
                            Points = 1,
                            QuestionText = "What should you do before opening car door?"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Traffic Signs",
                            CorrectAnswer = "Proceed with caution",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Stop\", \"Proceed with caution\", \"Speed up\", \"Turn around\"]",
                            Points = 1,
                            QuestionText = "What does a flashing amber light mean?"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Road Rules",
                            CorrectAnswer = "Anticipating hazards and driving safely",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Driving aggressively\", \"Anticipating hazards and driving safely\", \"Speeding\", \"Ignoring rules\"]",
                            Points = 1,
                            QuestionText = "What is defensive driving?"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Road Rules",
                            CorrectAnswer = "When approaching another vehicle",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Never\", \"When approaching another vehicle\", \"Only in city\", \"Only on highways\"]",
                            Points = 1,
                            QuestionText = "When should you dip your headlights?"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Traffic Signs",
                            CorrectAnswer = "Maximum legal speed",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Minimum speed\", \"Maximum legal speed\", \"Recommended speed\", \"Average speed\"]",
                            Points = 1,
                            QuestionText = "What does a speed limit sign indicate?"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Road Safety",
                            CorrectAnswer = "Human error",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Weather\", \"Human error\", \"Road conditions\", \"Vehicle defects\"]",
                            Points = 1,
                            QuestionText = "What is the primary cause of road accidents?"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Road Rules",
                            CorrectAnswer = "To warn others of danger",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"To greet friends\", \"To warn others of danger\", \"In traffic jams\", \"At night\"]",
                            Points = 1,
                            QuestionText = "When should you use horn?"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Road Rules",
                            CorrectAnswer = "Slow down and check all directions",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Speed through\", \"Slow down and check all directions\", \"Close eyes\", \"Honk continuously\"]",
                            Points = 1,
                            QuestionText = "What is the safest way to cross an intersection?"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Emergency",
                            CorrectAnswer = "Stop, assist, and report",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Drive away\", \"Stop, assist, and report\", \"Ignore it\", \"Take photos only\"]",
                            Points = 1,
                            QuestionText = "What should you do in case of an accident?"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Road Markings",
                            CorrectAnswer = "Reserved lane marking",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Bus stop\", \"Reserved lane marking\", \"Parking\", \"Speed bump\"]",
                            Points = 1,
                            QuestionText = "What does a white diamond road marking indicate?"
                        },
                        new
                        {
                            Id = 43,
                            Category = "Road Rules",
                            CorrectAnswer = "Look over shoulder and use mirrors",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Use mirrors only\", \"Look over shoulder and use mirrors\", \"Close eyes\", \"Speed up\"]",
                            Points = 1,
                            QuestionText = "What is the correct procedure for reversing?"
                        },
                        new
                        {
                            Id = 44,
                            Category = "Road Rules",
                            CorrectAnswer = "Near pedestrian crossings",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"On open road\", \"Near pedestrian crossings\", \"On highways\", \"During daytime\"]",
                            Points = 1,
                            QuestionText = "When is it illegal to overtake?"
                        },
                        new
                        {
                            Id = 45,
                            Category = "Vehicle Knowledge",
                            CorrectAnswer = "Fuel, tires, lights, mirrors",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Nothing\", \"Fuel, tires, lights, mirrors\", \"Radio\", \"Air freshener\"]",
                            Points = 1,
                            QuestionText = "What should you check before starting a journey?"
                        },
                        new
                        {
                            Id = 46,
                            Category = "Traffic Signs",
                            CorrectAnswer = "Stop",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Yield\", \"Stop\", \"Warning\", \"Information\"]",
                            Points = 1,
                            QuestionText = "What does an octagonal sign indicate?"
                        },
                        new
                        {
                            Id = 47,
                            Category = "Road Rules",
                            CorrectAnswer = "Pull over and stop",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Speed up\", \"Pull over and stop\", \"Follow it\", \"Block it\"]",
                            Points = 1,
                            QuestionText = "What is the correct action when emergency vehicle approaches?"
                        },
                        new
                        {
                            Id = 48,
                            Category = "Road Safety",
                            CorrectAnswer = "Below speed limit",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Speed limit\", \"Below speed limit\", \"Above speed limit\", \"Maximum speed\"]",
                            Points = 1,
                            QuestionText = "What is the safest speed in adverse weather?"
                        },
                        new
                        {
                            Id = 49,
                            Category = "Road Safety",
                            CorrectAnswer = "For children under specified age/weight",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Never\", \"For children under specified age/weight\", \"Only on highways\", \"Only in back seat\"]",
                            Points = 1,
                            QuestionText = "When should child seats be used?"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Traffic Signs",
                            CorrectAnswer = "Guide, warn, and regulate traffic",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Options = "[\"Decoration\", \"Guide, warn, and regulate traffic\", \"For birds\", \"No purpose\"]",
                            Points = 1,
                            QuestionText = "What is the purpose of road signs?"
                        });
                });

            modelBuilder.Entity("SmartLicenseAPI.Models.ExamAnswer", b =>
                {
                    b.HasOne("SmartLicenseAPI.Models.ExamSession", "ExamSession")
                        .WithMany()
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartLicenseAPI.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamSession");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("SmartLicenseAPI.Models.ExamSession", b =>
                {
                    b.HasOne("SmartLicenseAPI.Models.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });
#pragma warning restore 612, 618
        }
    }
}
